# theme: jekyll-theme-minimal
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            Nabla Containers
tagline:          'A new approach to Container Isolation'
description:      'A new approach to Container Isolation'
url:              https://nabla-containers.github.io
baseurl:          /

author:
  name:           'TBD'
  url:            https://twitter.com/

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/nabla-containers

collections:
  authors:
    output: true

defaults:
- scope:
    path: ""
    type: authors
  values:
    picture: "default.png" 
